### PR TITLE
Login

### PR DESCRIPTION
**Pull request by huntermetts**
# Description
When user clicks "tasks" they will be prompted to enter their credentials (username and password) 

## Type of change
- [X] New feature (non-breaking change which adds functionality)

# Testing Instructions for Change Made
1. `git fetch --all`
2. `git checkout login`
3. Check to see that when you click "tasks" in the navbar that the user must be "logged in".

# Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by huntermetts** [comment]
Also! make sure in your devtools under  the "application" tab that there is nothing in session storage when the app loads

**Review by THATBLADEBOY — APPROVED** [review]
Dope fresh 👌

**Review by emmettSchneider — CHANGES_REQUESTED** [review]
Suggest changing the login to use username instead of email address.

**Review by emmettSchneider — APPROVED** [review]
Works as advertised. Approved.

**Pull request merged**
